XOR unaviable, docker aviable

diff --git a/bot/Dockerfile b/bot/Dockerfile
--- a/bot/Dockerfile
+++ b/bot/Dockerfile
@@ -1,21 +1,9 @@
-# Базовый образ Node.js (легковесная версия на Alpine Linux)
-FROM node:18-alpine
-
-# Создаём рабочую директорию в контейнере
+FROM node:20.5.0
 WORKDIR /app
-
-# Копируем package.json и package-lock.json
 COPY package*.json ./
-
-# Устанавливаем зависимости
+ENV NODE_ENV=development
 RUN npm install
-
-# Копируем весь проект внутрь контейнера
+RUN npm list typescript && ls -l node_modules/.bin/tsc || echo "tsc missing"
 COPY . .
-
-# Собираем TypeScript
 RUN npm run build
-
-# Задаём команду, которая будет выполняться при запуске контейнера
-# Для dev-режима может быть и "npm run dev", но сейчас для примера укажем старт продакшн-сборки
-CMD ["npm", "run", "start:prod"]
+CMD ["npm", "run", "dev"]
